var QS = [
  {
    // "productivity": [
    //   "If I could work on one thing only today to be happy, what would it be?",
    //   "Can this goal be any more concrete?",
    //   "How can I use more of my potential or time?",
    //   "What could you be doing right now to accomplish the task?",
    //   "If you had 1 million dollars right now, how would you proceed?",
    //   "What would you need to solve that problem?",
    //   "What can I show people for today?",
    //   "What is the next step?",
    //   "What are the next three steps that you can take?",
    //   "What is the problem with that?",
    //   "Is there anything else stopping you from doing that?",
    //   "What would make this more fun?",
    //   "Why did I not do that task?",
    //   "Is there a clear and well-lit path to do it?",
    //   "What is my ideal day?",
    //   "What is the simple step forward?",
    //   "What is my perfect environment?",
    //   "How do I want to do that, concretely?",
    //   "What task is the most important?",
    //   "Is this task more important than that task?",
    //   "Why is the next task more important?",
    //   "Who are the people who could help me solve that problem?",
    //   "Who could know people who could help you solve that problem?"
    // ],
    // "outside the box": [
    //   "How do I make it so that I have no job other than breaking the system?",
    //   "Where do you see room for improvement?",
    //   "How do I think 10x bigger from the beginning?",
    //   "How would most people solve this?",
    //   "How can it be done differently?",
    //   "Would the opposite work?",
    //   "Who is good at this who shouldn't be?",
    //   "How can I change this to lead to new thoughts?",
    //   "What is actually out there?",
    //   "What are people following that might not be true?",
    //   "What really works and what is an untruth assumption?"
    // ],
    // "planning" : [
    //   "What do I have?",
    //   "What do I need to accomplish that task?",
    //   "What am I good at?",
    //   "What am I bad at?",
    //   "What are my long-term goals?",
    //   "What are my short-term goals?",
    //   "What am I passionate about?"
    // ],
    // "learning": [
    //   "What do I want to learn now?",
    //   "What is the MED?",
    //   "What is the minimum information that will enable me to play?"
    // ],
    "goal review checklist": [
      "What's the X to Y by when?",
      "What is the result?",
      "Is it challenging?",
      "Is it exciting?",
      "Is it relevant?",
      "What's in it for me?",
      "Can I progress now?",
      "What's the next move (physically specific?)?",
      "Who can help me?"
    ],
    // "indecisiveness": [
    //   "Is this right?",
    //   "What is it for?",
    //   "Why should I do this?",
    //   "Do I feel alive in this moment?",
    //   "Do I really want to do that?",
    //   "What is the plan?",
    //   "​Can anyone else do it?",
    //   "Is that the reason why you are doing this?",
    //   "What would happen when that did not work?"
    // ],
    // "humility" : [
    //   "How to shift focus from oneself?​",
    //   "How can I do this for others?",
    //   "Do outsiders get the benefit of the doubt?",
    //   "Do we make it easy for outsiders to become insiders?"
    // ],
    // "welness": [
    //   "Am I in a bad mood?",
    //   "Am I happy now?",
    //   "What makes me angry?",
    //   "What annoys me?"
    // ],
    // "meta": [
    //   "What questions should I be asking myself?"
    // ],
    // "teaching": [
    //   "What do I want to teach people?",
    //   "Is there an interesting way to put it?",
    //   "How can I imagine this better?",
    //   "If I want people to take away one thing only, what is it?"
    // ],
    // "humanity": [
    //   "What do humans like to do and why?"
    // ],
    // "motivation": [
    //   "Can you make change happen?",
    //   "How can I become limitless?",
    //   "How do I crush it today?",
    //   "Am I a man of circumstance?",
    //   "Am I excusing myself?",
    //   "Am I pushing myself mentally today?",
    //   "Do you think you can change the world?"
    // ],
    // "writing": [
    //   "What are some things that I find myself explaining again and again?",
    //   "What is the story?"
    // ],
    // "interview": [
    //   "Where do you see yourself in 5 years?",
    //   "Why do you want to work for us?"
    // ],
    // "get to know": [
    //   "What is your favorite book?",
    //   "What is your favorite movie?",
    //   "What is your dream job?",
    //   "What dreams do you have?",
    //   "What do you think often about?",
    //   "What area of expertise interests you?",
    //   "How do you see the future?",
    //   "What can you teach?"
    // ],
    // "education": [
    //   "What was your education experience like?",
    //   "What do you think schools should focus more on?",
    //   "Do you think you can learn anything?"
    // ],
    "reminders": [
      "To imagine is human. Imagine.",
      "Assume it's not personal.",
      "Start with something you enjoy.",
      "Have faith in yourself.",
      "Stand up to your fear.",
      "Start with today.​",
      "Given enough eyeballs, all bugs are shallow.",
      "There is always a move.",
      "Giving yourself an F doesn't help.",
      "If you struggled and did something, at the end of the day, give yourself an A.",
      "Be physically specific. Then it will be painfully obvious.",
      "Commit.",
      "It's simple the moment you believe it's simple.",
      "Make learning conscious learning.",
      "A reminder that's not reminding is useless.",
      "It's better to waste effort than waste time.​",
      "Doing without thinking is mindless, thinking without doing is useless.​",
      "Go into nature.",
      "Do your part. The world may not do its, but if you do your best, you can't regret it.",
      "Live deliberately.​​",
      "There has to be an end.",
      "Be a member of small groups. Be an early adopter.",
      "Start with something you enjoy.​",
      "Be careful where you place blame. Blame is artificial construct, in the real world there are only causes.",
      "​Surround yourself with people who can, instead of can't.",
      "You already are limitless.​​",
      "Failure is getting discouraged.",
      "When writing: is the opposite absurd? If yes, then the information might be redundant.",
      "Get emotion, transcend reason.",
      "Define until everything is in front of you, waiting to be done.",
      "The only emotion allowed is enthusiasm or brief righteous anger.",
      "Every day is a chance for a new beginning.",
      "​Computer use is not synonymous with productivity.",
      "Before every meeting, ask yourself: what can I offer?",
      "There are no problems, only challenges.​",
      "When you are supposed to meet with someone, double check with them the time and place in advance.",
      "Broader knowledge leads to the ability to understand the opposite view.",
      "There is too much of selves, and to little of others today.",
      "Be an aggressive learner.​​​​​",
      "Build your business in a industry where your personality is a strength.",
      "The enemy of resistance is regularity.",
      "Judgment wastes energy.",
      "Make others think.​​",
      "Ill-defined is largely meaningless.",
      "When someone does something for you, be obviously grateful.",
      "Any way of materializing a project is better than none.",
      "Schedule changes of environment.",
      "With knowledge comes power to control, and with power to control comes confidence.",
      "Employees need to experience progress. Rituals, raises, revenue growth.",
      "No donuts in the morning.​",
      "​We think in differences.",
      "There is a bad way of doing a good thing.",
      "Remember what people do for you. Be grateful.",
      "Know the motivation of the people on your team.",
      "Failure is not learning.",
      "​Visual and aural experiences count as most vivid.",
      "Follow own advice thoroughly.",
      "​Take your mind with you when you go somewhere.",
      "The problem is not action, it's inaction.",
      "Send the right signals to strengthen the right circuits.",
      "Anything not working well should be reexamined.",
      "Train commitment in everything.​",
      "​If it was absolutely brilliant, would people come? Yes? Make it the best you can then.",
      "You are work in progress.",
      "Use anger as fuel to change the world.",
      "Doing something makes us happier than doing nothing (regret minimization framework).",
      "Cynicism is intelligence without hope.",
      "Don't make the choice to be cynical.",
      "A different opinion in a brainstorming foothold.​",
      "Doubt is the absence of action.",
      "Allow others to help you become who you want to be.",
      "Think shit through before you show up. Have at least three questions ready.",
      "Add for you to every question.",
      "Be that good, even if you don't care.",
      "Don't complain, don't point out flaws if you don't understand or don't have a solution.",
      "​Be so awesome that you create content by being.",
      "Work is not as painful as we imagine it to be.",
      "Inspire happiness.",
      "Be ridiculous.​​",
      "​Allow yourself to fail. Allow yourself to make mistakes.",
      "Listen more, tell less.",
      "Accept.​",
      "You create audience by creating value in the real world.",
      "Solve problems that are painful, and important.",
      "Rest before you drink coffee.",
      "Expectations determine satisfaction.",
      "Break up weekly goals.",
      "Work hard on the right things, you will get there eventually.",
      "Build a brand before partnerships.",
      "Be different.",
      "Protect your body & mind.",
      "​See people as allies by default.",
      "Be one unicorn of a kind.",
      "One connection can change your life.​",
      "Be the one who sews the seeds.",
      "Two choices is better than ten choices.",
      "You don't finish a task if you haven't started.",
      "Safe does not encourage resourceful.",
      "​Do good, enjoyable things other people can't do, or won't do.",
      "Try to give ideas away.",
      "​Instead of discovering yourself, create yourself.",
      "​Traveling forces flexibility.​",
      "Figure this out and you can help millions of other people.",
      "Let others speak.",
      "You have no responsibility to society.",
      "Redefine perspective.",
      "You're strong.",
      "Be tattoo-worthy.",
      "Effort is so good.",
      "​Embody a beautiful state, transfer it to others.",
      "Don't feel bad about any effort.",
      "You're more powerful than you think you are. Act accordingly.",
      "Don't assume malice."
    ]
  }
];
